name: Generic SLSA3 Bazel

on: 
    workflow_dispatch:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            hashes: ${{steps.hash.outputs.hashes}}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                persist-credentials: false
              
            - name: Setup Bazelisk
              uses: bazelbuild/setup-bazelisk@v2

            - name: Build Artifacts
              run: |
                bazel build //...
                cp bazel-bin/src/hello_dep .
                cp bazel-bin/src/world/HelloWorld .

            - name: Generate Provenance Subject
              id: hash
              run: |
                set -euo pipefail
                sha256sum hello_dep HelloWorld > checksums
                echo "hashes=$(cat checksums | base64 -w0)" >> "${GITHUB_OUTPUT}"

            - name: Upload Artifacts Part 1
              uses: actions/upload-artifact@v3
              with:
                name: hello_dep
                path: hello_dep
                if-no-files-found: error
                retention-days: 1
            
            - name: Upload Artifacts Part 2
              uses: actions/upload-artifact@v3
              with:
                name: HelloWorld
                path: HelloWorld
                if-no-files-found: error
                retention-days: 1

    provenance:
        needs: [build]
        permissions:
            actions: read # To read the workflow path.
            id-token: write # To sign the provenance.
            contents: write # To add assets to a release.
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.6.0
        with:
            base64-subjects: "${{ needs.build.outputs.hashes }}"
            upload-assets: true # Optional: Upload to a new release
            upload-tag-name: "v1.0.0"

    release:
        needs: [build, provenance]
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
          - name: Download hello_dep artifact
            uses: actions/download-artifact@v3
            with:
              name: hello_dep
          - name: Download HelloWorld artifact
            uses: actions/download-artifact@v3
            with:
              name: HelloWorld
          - name: Upload assets
            uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
            with:
              files: |
                hello_dep
                HelloWorld